msvc-eureka:
  property: msvc-eureka profile dev

server:
  port: 8763

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/

